kind: PersistentVolume
apiVersion: v1
metadata:
    name: pv-storage
    labels:
        type: local
spec:
     capacity:
        storage: 2Gi
     accessModes:
     -  ReadWriteOnce
     hostPath:
         path: “/mydata”